server:
  port: 8765

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loginandregist?serverTimezone=UTC
    username: root
    password: csh20011103
    # 如果用其他数据源可以用type来定义
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka